title: The ExTrEMe Collaboration
email: mluzum@usp.br
description: EXperiment and TheoRy in Extreme MattEr
baseurl: ""
url: ""
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
header_pages:
  - members.md
  - publications.md
  - simulation-chain.md
  - presentations.md
  - wiki.md
  - contact.md
